export enum GameActions {
    END_GAME = 'END_GAME',
    CREATE_GAME = 'CREATE_GAME',
    START_GAME = 'START_GAME',
    RESTART_GAME = 'RESTART_GAME',
    JOIN_GAME = 'JOIN_GAME',
    ACTION = 'ACTION',
}
